### PR TITLE
Documentation/test clean-up; add protobuf_segment_message/2

### PR DESCRIPTION
**Pull request by kamahen**
protobuf_segment_message/2 emulates the output from `protoc --decode_raw` - it's a first step towards more general protobuf processing and maybe even a compiler to Prolog. Some of the preliminary work is in
*  demo/descriptor_proto_expand.pl
    (used in demo/descriptor_proto.pl)
*  parse_descriptor_proto_dump.pl

I've also exposed the low-level field32_codes/2, etc. because they're useful elsewhere.

I've edited some of the documentation to Markdown (not sure that this is correct -- it was in SWI-Prolog wiki markup, which didn't display nicely on github) and done a bit of editing to the documentation.

And I've added some comments and more code to demo/vector_demo.pl

New files added - some may be removed in future, being part of a bootstrap for a protobuf compiler (see Issue #1)
- README.md (incomplete)
- descriptor_proto.dump
- descriptor_proto.pl
- descriptor_proto_expand.pl
- parse_descriptor_proto_dump.pl

### CODE REVIEW

**Comment by kamahen** [comment]
I tried contacting Jeffrey Rosenwald (JeffRose@acm.org), in case he wants to comment on my changes; but the email bounced.

**Comment by JanWielemaker** [comment]
I've granted you access to the repo.   I browsed to some of the commits.   I think it is all in good style.  If it all builds and runs the tests just go along with it.

**Comment by kamahen** [comment]
I've rebased the PR and pushed to github separately.

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/does-anyone-care-about-protobufs/3860/19

**Pull request closed without merging**
